"""Add grading formula to Class

Revision ID: 12951fa0016e
Revises: d11110673a42
Create Date: 2026-02-13 09:17:15.626205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12951fa0016e'
down_revision = 'd11110673a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('subject_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('units', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('grading_formula', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('grade_conversion_table', sa.Text(), nullable=True))
        batch_op.alter_column('subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.alter_column('subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('grade_conversion_table')
        batch_op.drop_column('grading_formula')
        batch_op.drop_column('units')
        batch_op.drop_column('subject_code')
        batch_op.drop_column('subject_name')

    # ### end Alembic commands ###
