"""empty message

Revision ID: 6b31130f5732
Revises: b7e21f3c8d04
Create Date: 2026-03-16 11:14:13.683413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b31130f5732'
down_revision = 'b7e21f3c8d04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_score', sa.Float(), nullable=True))

    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_class_term_component'))

    with op.batch_alter_table('test_paper_image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_paper_image_test_status'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_paper_image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_paper_image_test_status'), ['test_id', 'status'], unique=False)

    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_class_term_component'), ['class_id', 'term_tag', 'component_tag'], unique=False)

    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.drop_column('max_score')
        batch_op.drop_column('raw_score')

    # ### end Alembic commands ###
